export const SET_MOVIES_NOW_PLAYING = 'SET_MOVIES_NOW_PLAYING';
export const SET_MOVIES_POPULAR = 'SET_MOVIES_POPULAR';
export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
export const SET_ALL_GENRES = 'SET_ALL_GENRES';